#!/usr/bin/env bash

# Showcase some colours.
# Yes, colours has a U in it.

echo This is normal text
echo -e "${red}This colour is red.${nocol}"
echo -e "${green}This colours is green.${nocol}"
echo -e "${blue}This colours is blue.${nocol}"
echo -e "${yellow}This colours is yellow.${nocol}"
echo -e "${bold}This colour is bold.${nocol}"

