"###### Start Vundle Stuff #######
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/syntastic'
Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-fugitive'
Plugin 'Shutnik/jshint2.vim'
Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'mattn/emmet-vim'

" Colorschemes
Plugin 'zsoltf/vim-maui'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

"###### End Vundle Stuff #######


" Set tabs to 2 spaces
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set autoindent

" ..except in python files use four spaces to indent
autocmd FileType python setlocal shiftwidth=4 tabstop=8 softtabstop=4

" Turn on line numbers
set number

" Automatically detect file types
filetype on

" Interpret .md files as markdown
au BufNewFile,BufFilePre,BufRead *.md set filetype=markdown

" Set current window at least 84 wide and as tall as possible
" while leaving other windows 5 lines tall
"set winwidth=84
"set winheight=5
"set winminheight=5
"set winheight=999

" Make it look pretty
set t_Co=256

if &t_Co > 2 || has ("gui_running")
  syntax on
  set hlsearch
endif

set background=dark
colorscheme maui

set ruler

" Gohu font: http://font.gohu.eu/
set guifont=gohufont-14

"#### keyboard shortcuts ####

" Colourscheme browsing
map <silent><f2> :PREVCOLOR<cr>
map <silent><f3> :NEXTCOLOR<cr>

" Code folding
map <silent><F5> zfa}
map <silent><F6> zo
map <silent><F7> zc

" Enable CTRL+HJKL window splitting
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Use tab for Emmet completion
imap <expr> <tab> emmet#expandAbbrIntelligent("\<tab>")

" Toggle Nerdtree with ^n
map <C-n> :NERDTreeToggle<CR>

" Split to bottom right
set splitbelow
set splitright

" Show containing folder - ctrl-f5
if has("gui_running")
  if has("win32")
    :map <silent> <C-F5> :if expand("%:p:h") != ""<CR>:!start explorer.exe %:p:h<CR>:endif<CR><CR>
  endif
endif

" Taglist Shortcut
" Requires Vim-Taglist - http://vim-taglist.sourceforge.net/
" Which in turn requires Exuberant Ctags - http://ctags.sourceforge.net/
nnoremap <silent><F9> :TlistToggle<CR>

" NERDTree file browser
" map <silent><F10> :NERDTree C:/XAMPP/htdocs<cr><cr>

" Use unix line endings
set ff=unix

" Show nerdtree on startup if there's nothing else to do
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" Exit vim if only nerdtree is open
"autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

" Allow using mouse to resize splits within Tmux
set mouse+=a
if &term =~ '^screen'
  " tmux knows the extended mouse mode
  set ttymouse=xterm2
endif

