# Set up some colours
red="\e[0;31m"
green="\e[0;32m"
yellow="\e[0;33m"
blue="\e[0;34m"
nocol="\e[0m"
bold="\e[1m"
dim="\e[2m"

  echo ""
  echo -e ${yellow}Press ctrl+a and then...${nocol}
  echo ""
  echo -e "${blue}Tmux Commands${nocol}                             ${blue}Windows (Tab)${nocol}"
  echo -e " ${yellow}List${nocol}    ls                                ${yellow}Create${nocol}      c"
  echo -e " ${yellow}New${nocol}     -s <session>                      ${yellow}Close${nocol}       &"
  echo -e " ${yellow}Attach${nocol}  att -t <session>                  ${yellow}List${nocol}        w"
  echo -e " ${yellow}Kill${nocol}    kill-session -t <session>         ${yellow}Rename${nocol}      , <name>"
  echo -e " ${yellow}Rename${nocol}  rename-session -t <old> <new>     ${yellow}Last${nocol}        l"
  echo -e " ${yellow}Goto${nocol} #      <0-9>                         ${yellow}Next${nocol}        n"
  echo -e "                                           ${yellow}Previous${nocol}    p"
  echo -e ""
  echo -e "${blue}Controls${nocol}                                 ${blue}Panes (Split Window)${nocol}"
  echo -e " ${yellow}Choose${nocol}     w <name>                      ${yellow}Show nums${nocol}   q"
  echo -e " ${yellow}Detach${nocol}     d                             ${yellow}Split Horiz${nocol} \""
  echo -e " ${yellow}List${nocol}       =                             ${yellow}Split Vert${nocol}  %"
  echo -e " ${yellow}Buffer${nocol}     PAGEUPDN                      ${yellow}Pane>Window${nocol} !"
  echo -e " ${yellow}Command${nocol}    : <command>                   ${yellow}Kill${nocol}        x"
  echo -e " ${yellow}Paste${nocol}      p                             ${yellow}Reorganize${nocol}  SPACE"
  echo -e " ${yellow}Copy Mode${nocol}  ESC                           ${yellow}Expand${nocol}      ALT+ARROW"
  echo -e "    - ${yellow}Move${nocol}  hjkl                          ${yellow}Resize${nocol}      CTRL+ARROW"
  echo -e "    - ${yellow}Start${nocol} v                             ${yellow}Resize x n${nocol}  <n> ARROW"
  echo -e "    - ${yellow}Copy${nocol}  y                             ${yellow}Select${nocol}      ARROW"
  echo -e "                                          ${yellow}Previous${nocol}    {"
  echo -e "${blue}Sessions (Set of window)${nocol}                  ${yellow}Next${nocol}        }"
  echo -e " ${yellow}New${nocol}      :new [-s <name>]                ${yellow}Switch${nocol}      o"
  echo -e " ${yellow}Rename${nocol}   $                               ${yellow}Swap${nocol}        ^o"
  echo -e " ${yellow}List${nocol}     s                               ${yellow}Last${nocol}        ;"
  echo -e " ${yellow}Next${nocol}     ("
  echo -e " ${yellow}Previous${nocol} )"
  